language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer update $COMPOSER_FLAGS
  - composer validate

script: bin/phpunit
